export const $tipoMovimiento: { [key: string]: string } = {
    "MON": "MONOUSUARIO",
    "SRV": "SERVIDOR",
    "RED": "TERMINAL DE RED",
    "SR0": "SERVIDOR EMPRESARIAL",
    "SR1": "SERVIDOR EMPRESARIAL",
    "SR2": "SERVIDOR EMPRESARIAL",
    "SR3": "SERVIDOR EMPRESARIAL",
    "SR4": "SERVIDOR EMPRESARIAL",
    "SR5": "SERVIDOR EMPRESARIAL",
    "SR6": "SERVIDOR EMPRESARIAL",
    "SR7": "SERVIDOR EMPRESARIAL",
    "SR8": "SERVIDOR EMPRESARIAL",
    "SR9": "SERVIDOR EMPRESARIAL",
    "CFDI": "Folios de Facturas para generar CFDI",
    "IEDU": "Complemento para la expedición de las facturas por parte de las Instituciones Educativas Privadas",
    "DIV": "Complemento de Dividendos incluido en el CFDI de Retenciones",
    "RET": "CFDI de Retenciones incluye Dividendos",
    "TRAS": "CFDI de Traslado para Transportistas",
    "CEX": "Comercio Exterior",
    "NOT": "Complemento de Notarios Públicos manejo de la enajenación de bienes inmuebles",
    "LF": "Complemento de Leyendas Fiscales",
    "INE": "Complemento es la información adicional en los CFDI emitidos por la prestación de un servicio en las precampañas y campañas políticas.",
    "PCO": "Complemento para el prestador de servicios parciales de construcción de inmuebles destinados a casa habitación",
    "DON": "Donatarios",
    "TER": "Complemento para los comisionista, prestadores de servicios de cobranza o Notarios Públicos"
}